### ISSUE TITLE
Can't perform mysqldump on WP Engine

### ISSUE THREAD

**Issue by csalzano** [csalzano/exfil#18]
No permissions to run `mysqldump` on WP Engine

**Comment by csalzano** [comment]
- [ ] Detect WP Engine
- [ ] Download `/wp-content/mysql.sql` instead of running a mysqldump

**Comment by eriktdesign** [comment]
Fun fact -- I found your issue here while I was googling for the same problem trying a site migration. You should be able to run the `mysqldump` by using the `--no-tablespaces` flag.

This command worked for me in a WPE site environment:
```
mysqldump --no-create-info --skip-triggers --add-drop-table --no-tablespaces --user=username wp_databasename wp_usermeta --where="user_id >= 9000000" > wp_usermeta_gte_9000000.sql
```

Probably irrelevant as a 2 year old issue -- but I saw a familiar face randomly 😄

**Comment by csalzano** [comment]
Well well well. I closed our WP Engine account a couple weeks ago, so until one my clients with them resurfaces, I don't have any way or desire to test! I'm reopening this issue, but I'm not sure if that will help me remember when this eventually happens. Thanks!
